/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_espejo_ejer;

/**
 *
 * @author Miguel
 */
public class interfazEspejo extends javax.swing.JFrame {

    /**
     * Creates new form interfazEspejo
     */
    public interfazEspejo() {
        initComponents();
        buttonGroup1.add(this.rbtnOriginalOpcion1);
        buttonGroup1.add(this.rbtnOriginalOpcion2);
        buttonGroup1.add(this.rbtnOriginalOpcion3);
        
        buttonGroup2.add(this.chboxImitacionOpcion4);
        buttonGroup2.add(this.chboxImitacionOpcion5);
        buttonGroup2.add(this.chboxImitacionOpcion6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        lblOriginal = new javax.swing.JLabel();
        rbtnOriginalOpcion1 = new javax.swing.JRadioButton();
        rbtnOriginalOpcion2 = new javax.swing.JRadioButton();
        rbtnOriginalOpcion3 = new javax.swing.JRadioButton();
        chboxOriginalOpcion4 = new javax.swing.JCheckBox();
        chboxOriginalOpcion5 = new javax.swing.JCheckBox();
        chboxOriginalOpcion6 = new javax.swing.JCheckBox();
        txOriginaltPrueba1 = new javax.swing.JTextField();
        cboxOriginalItem = new javax.swing.JComboBox();
        SpinnerOriginalPrueba1 = new javax.swing.JSpinner();
        lblEspejo = new javax.swing.JLabel();
        rbtnImitacionOpcion1 = new javax.swing.JRadioButton();
        rbtnImitacionOpcion2 = new javax.swing.JRadioButton();
        chboxImitacionOpcion4 = new javax.swing.JCheckBox();
        chboxImitacionOpcion5 = new javax.swing.JCheckBox();
        rbtnImitacionOpcion3 = new javax.swing.JRadioButton();
        chboxImitacionOpcion6 = new javax.swing.JCheckBox();
        SpinnerImitacionPrueba1 = new javax.swing.JSpinner();
        txtImitaciontPrueba1 = new javax.swing.JTextField();
        cboxImitacionItem = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);

        lblOriginal.setText("Original");

        rbtnOriginalOpcion1.setText("Opcion 1");
        rbtnOriginalOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOriginalOpcion1ActionPerformed(evt);
            }
        });

        rbtnOriginalOpcion2.setText("Opcion 2");
        rbtnOriginalOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOriginalOpcion2ActionPerformed(evt);
            }
        });

        rbtnOriginalOpcion3.setText("Opcion 3");
        rbtnOriginalOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOriginalOpcion3ActionPerformed(evt);
            }
        });

        chboxOriginalOpcion4.setText("Opcion 4");
        chboxOriginalOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxOriginalOpcion4ActionPerformed(evt);
            }
        });

        chboxOriginalOpcion5.setText("Opcion 5");
        chboxOriginalOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxOriginalOpcion5ActionPerformed(evt);
            }
        });

        chboxOriginalOpcion6.setText("Opcion 6");
        chboxOriginalOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxOriginalOpcion6ActionPerformed(evt);
            }
        });

        txOriginaltPrueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txOriginaltPrueba1ActionPerformed(evt);
            }
        });

        cboxOriginalItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEspejo.setText("Espejo");

        rbtnImitacionOpcion1.setText("jRadioButton1");
        rbtnImitacionOpcion1.setEnabled(false);

        rbtnImitacionOpcion2.setText("jRadioButton2");
        rbtnImitacionOpcion2.setEnabled(false);

        chboxImitacionOpcion4.setText("jCheckBox1");
        chboxImitacionOpcion4.setEnabled(false);

        chboxImitacionOpcion5.setText("jCheckBox2");
        chboxImitacionOpcion5.setEnabled(false);

        rbtnImitacionOpcion3.setText("jRadioButton3");
        rbtnImitacionOpcion3.setEnabled(false);

        chboxImitacionOpcion6.setText("jCheckBox3");
        chboxImitacionOpcion6.setEnabled(false);

        SpinnerImitacionPrueba1.setEnabled(false);

        txtImitaciontPrueba1.setText("jTextField1");
        txtImitaciontPrueba1.setEnabled(false);

        cboxImitacionItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxImitacionItem.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOriginal)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnOriginalOpcion1)
                                    .addComponent(rbtnOriginalOpcion2)
                                    .addComponent(rbtnOriginalOpcion3))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(chboxOriginalOpcion4)
                                        .addGap(55, 55, 55)
                                        .addComponent(txOriginaltPrueba1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chboxOriginalOpcion5)
                                            .addComponent(chboxOriginalOpcion6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboxOriginalItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SpinnerOriginalPrueba1)))))
                            .addComponent(lblEspejo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnImitacionOpcion1)
                                    .addComponent(rbtnImitacionOpcion2)
                                    .addComponent(rbtnImitacionOpcion3))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(chboxImitacionOpcion4)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtImitaciontPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chboxImitacionOpcion5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(chboxImitacionOpcion6)
                                                .addGap(58, 58, 58)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboxImitacionItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SpinnerImitacionPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOriginalOpcion1)
                    .addComponent(chboxOriginalOpcion4)
                    .addComponent(txOriginaltPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOriginalOpcion2)
                    .addComponent(chboxOriginalOpcion5)
                    .addComponent(cboxOriginalItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOriginalOpcion3)
                    .addComponent(chboxOriginalOpcion6)
                    .addComponent(SpinnerOriginalPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEspejo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnImitacionOpcion1)
                    .addComponent(chboxImitacionOpcion4)
                    .addComponent(txtImitaciontPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnImitacionOpcion2)
                    .addComponent(chboxImitacionOpcion5)
                    .addComponent(cboxImitacionItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnImitacionOpcion3)
                    .addComponent(chboxImitacionOpcion6)
                    .addComponent(SpinnerImitacionPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chboxOriginalOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxOriginalOpcion4ActionPerformed
        // TODO add your handling code here:
        this.chboxImitacionOpcion4.setSelected(this.chboxOriginalOpcion4.isSelected());
    }//GEN-LAST:event_chboxOriginalOpcion4ActionPerformed

    private void rbtnOriginalOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOriginalOpcion1ActionPerformed
//       rbtnImitacionOpcion1.setSelected(rbtnOriginalOpcion1.isSelected());
        this.rbtnImitacionOpcion1.setSelected(this.rbtnOriginalOpcion1.isSelected());

    }//GEN-LAST:event_rbtnOriginalOpcion1ActionPerformed

    private void txOriginaltPrueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txOriginaltPrueba1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txOriginaltPrueba1ActionPerformed

    private void rbtnOriginalOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOriginalOpcion2ActionPerformed
        //rbtnImitacionOpcion2.setSelected(rbtnOriginalOpcion2.isSelected());
        this.rbtnImitacionOpcion2.setSelected(this.rbtnOriginalOpcion2.isSelected());
    }//GEN-LAST:event_rbtnOriginalOpcion2ActionPerformed

    private void rbtnOriginalOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOriginalOpcion3ActionPerformed
        //rbtnImitacionOpcion3.setSelected(rbtnOriginalOpcion3.isSelected());
        this.rbtnImitacionOpcion3.setSelected(this.rbtnOriginalOpcion3.isSelected());
    }//GEN-LAST:event_rbtnOriginalOpcion3ActionPerformed

    private void chboxOriginalOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxOriginalOpcion5ActionPerformed
        this.chboxImitacionOpcion5.setSelected(this.chboxOriginalOpcion5.isSelected());
    }//GEN-LAST:event_chboxOriginalOpcion5ActionPerformed

    private void chboxOriginalOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxOriginalOpcion6ActionPerformed
        this.chboxImitacionOpcion6.setSelected(this.chboxOriginalOpcion6.isSelected());
    }//GEN-LAST:event_chboxOriginalOpcion6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazEspejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazEspejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerImitacionPrueba1;
    private javax.swing.JSpinner SpinnerOriginalPrueba1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboxImitacionItem;
    private javax.swing.JComboBox cboxOriginalItem;
    private javax.swing.JCheckBox chboxImitacionOpcion4;
    private javax.swing.JCheckBox chboxImitacionOpcion5;
    private javax.swing.JCheckBox chboxImitacionOpcion6;
    private javax.swing.JCheckBox chboxOriginalOpcion4;
    private javax.swing.JCheckBox chboxOriginalOpcion5;
    private javax.swing.JCheckBox chboxOriginalOpcion6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEspejo;
    private javax.swing.JLabel lblOriginal;
    private javax.swing.JRadioButton rbtnImitacionOpcion1;
    private javax.swing.JRadioButton rbtnImitacionOpcion2;
    private javax.swing.JRadioButton rbtnImitacionOpcion3;
    private javax.swing.JRadioButton rbtnOriginalOpcion1;
    private javax.swing.JRadioButton rbtnOriginalOpcion2;
    private javax.swing.JRadioButton rbtnOriginalOpcion3;
    private javax.swing.JTextField txOriginaltPrueba1;
    private javax.swing.JTextField txtImitaciontPrueba1;
    // End of variables declaration//GEN-END:variables
}
