/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_interfaces_graficas_miguel_1;

/**
 *
 * @author Miguel
 */
public class espejo2 extends javax.swing.JFrame {

    /**
     * Creates new form espejo2
     */
    public espejo2() {
        initComponents();
        buttonGroup1.add(rdb1Original);
        buttonGroup1.add(rdb2Original);
        buttonGroup1.add(rdb3Original);

        buttonGroup2.add(rdb1Imitacion);
        buttonGroup2.add(rdb2Imitacion);
        buttonGroup2.add(rdb3Imitacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdb1Original = new javax.swing.JRadioButton();
        rdb2Original = new javax.swing.JRadioButton();
        rdb3Original = new javax.swing.JRadioButton();
        lblOriginal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblImitacion1 = new javax.swing.JLabel();
        rdb1Imitacion = new javax.swing.JRadioButton();
        rdb2Imitacion = new javax.swing.JRadioButton();
        rdb3Imitacion = new javax.swing.JRadioButton();
        ckb2Original = new javax.swing.JCheckBox();
        ckb3Original = new javax.swing.JCheckBox();
        ckb1Original = new javax.swing.JCheckBox();
        ckb1Imitacion = new javax.swing.JCheckBox();
        ckb2Imitacion = new javax.swing.JCheckBox();
        ckb3Imitacion = new javax.swing.JCheckBox();
        txtOriginal = new javax.swing.JTextField();
        cmbOriginal = new javax.swing.JComboBox();
        spnOriginal = new javax.swing.JSpinner();
        txtImitacion = new javax.swing.JTextField();
        cmbImitacion = new javax.swing.JComboBox();
        spnImitacion = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdb1Original.setText("Opcion 1");
        rdb1Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1OriginalActionPerformed(evt);
            }
        });

        rdb2Original.setText("Opcion2 ");
        rdb2Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2OriginalActionPerformed(evt);
            }
        });

        rdb3Original.setText("Opcion3");
        rdb3Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb3OriginalActionPerformed(evt);
            }
        });

        lblOriginal.setText("Original");

        lblImitacion1.setText("Espejo");
        lblImitacion1.setEnabled(false);

        rdb1Imitacion.setText("Opcion 1");
        rdb1Imitacion.setEnabled(false);

        rdb2Imitacion.setText("Opcion2 ");
        rdb2Imitacion.setEnabled(false);

        rdb3Imitacion.setText("Opcion3");
        rdb3Imitacion.setEnabled(false);

        ckb2Original.setText("Opcion5");
        ckb2Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb2OriginalActionPerformed(evt);
            }
        });

        ckb3Original.setText("Opcion6");
        ckb3Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb3OriginalActionPerformed(evt);
            }
        });

        ckb1Original.setText("Opcion4");
        ckb1Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb1OriginalActionPerformed(evt);
            }
        });

        ckb1Imitacion.setText("Opcion4");
        ckb1Imitacion.setEnabled(false);

        ckb2Imitacion.setText("Opcion5");
        ckb2Imitacion.setEnabled(false);

        ckb3Imitacion.setText("Opcion6");
        ckb3Imitacion.setEnabled(false);

        txtOriginal.setText("jTextField1");
        txtOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOriginalKeyReleased(evt);
            }
        });

        cmbOriginal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOriginalItemStateChanged(evt);
            }
        });

        spnOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnOriginalStateChanged(evt);
            }
        });

        txtImitacion.setText("jTextField1");
        txtImitacion.setEnabled(false);

        cmbImitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbImitacion.setEnabled(false);

        spnImitacion.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdb3Imitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb2Imitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb1Imitacion)
                            .addComponent(lblImitacion1))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckb2Imitacion)
                            .addComponent(ckb3Imitacion)
                            .addComponent(ckb1Imitacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdb3Original, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb2Original, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb1Original, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOriginal))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckb1Original)
                            .addComponent(ckb2Original)
                            .addComponent(ckb3Original))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnOriginal)
                            .addComponent(cmbOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOriginal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnImitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb1Original)
                            .addComponent(ckb1Original)
                            .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb2Original)
                            .addComponent(ckb2Original)
                            .addComponent(cmbOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb3Original)
                            .addComponent(ckb3Original)
                            .addComponent(spnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImitacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdb1Imitacion)
                                .addGap(18, 18, 18)
                                .addComponent(rdb2Imitacion)
                                .addGap(18, 18, 18)
                                .addComponent(rdb3Imitacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckb1Imitacion)
                                .addGap(18, 18, 18)
                                .addComponent(ckb2Imitacion)
                                .addGap(18, 18, 18)
                                .addComponent(ckb3Imitacion)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb1OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1OriginalActionPerformed
        this.rdb1Imitacion.setSelected(this.rdb1Original.isSelected());
    }//GEN-LAST:event_rdb1OriginalActionPerformed

    private void rdb2OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2OriginalActionPerformed
        this.rdb2Imitacion.setSelected(this.rdb2Original.isSelected());
    }//GEN-LAST:event_rdb2OriginalActionPerformed

    private void rdb3OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb3OriginalActionPerformed
        this.rdb3Imitacion.setSelected(this.rdb3Original.isSelected());
    }//GEN-LAST:event_rdb3OriginalActionPerformed

    private void ckb1OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb1OriginalActionPerformed
        this.ckb1Imitacion.setSelected(this.ckb1Original.isSelected());
    }//GEN-LAST:event_ckb1OriginalActionPerformed

    private void ckb2OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb2OriginalActionPerformed
        this.ckb2Imitacion.setSelected(this.ckb2Original.isSelected());
    }//GEN-LAST:event_ckb2OriginalActionPerformed

    private void ckb3OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb3OriginalActionPerformed
        this.ckb3Imitacion.setSelected(this.ckb3Original.isSelected());
    }//GEN-LAST:event_ckb3OriginalActionPerformed

    private void txtOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyReleased
        this.txtImitacion.setText(this.txtOriginal.getText());
    }//GEN-LAST:event_txtOriginalKeyReleased

    private void cmbOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOriginalItemStateChanged
        //this.cmbImitacion.setSelectedItem(this.cmbOriginal.getSelectedItem());
        this.cmbImitacion.setSelectedIndex(this.cmbOriginal.getSelectedIndex());

    }//GEN-LAST:event_cmbOriginalItemStateChanged

    private void spnOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnOriginalStateChanged
        this.spnImitacion.setValue((Integer)this.spnOriginal.getValue());
    }//GEN-LAST:event_spnOriginalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(espejo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(espejo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(espejo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(espejo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new espejo2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox ckb1Imitacion;
    private javax.swing.JCheckBox ckb1Original;
    private javax.swing.JCheckBox ckb2Imitacion;
    private javax.swing.JCheckBox ckb2Original;
    private javax.swing.JCheckBox ckb3Imitacion;
    private javax.swing.JCheckBox ckb3Original;
    private javax.swing.JComboBox cmbImitacion;
    private javax.swing.JComboBox cmbOriginal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImitacion1;
    private javax.swing.JLabel lblOriginal;
    private javax.swing.JRadioButton rdb1Imitacion;
    private javax.swing.JRadioButton rdb1Original;
    private javax.swing.JRadioButton rdb2Imitacion;
    private javax.swing.JRadioButton rdb2Original;
    private javax.swing.JRadioButton rdb3Imitacion;
    private javax.swing.JRadioButton rdb3Original;
    private javax.swing.JSpinner spnImitacion;
    private javax.swing.JSpinner spnOriginal;
    private javax.swing.JTextField txtImitacion;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
